resitproject_new/resitproject_new/Models/StatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace resitproject_new.Models
{
    public class StatisticsViewModel
    {
        public string Title { get; set; }
        public string HebrewTitle { get; set; }
        public string[] Keys  { get; set; }
        public int[] Values { get; set; }
    }
}

resitproject_new/resitproject_new/Controllers/AbsencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using resitproject_new.Models;
using Microsoft.AspNet.Identity;
using resitproject_new.DAL;
using resitproject_new.BL;

namespace resitproject_new.Controllers
{
    public class AbsencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Absences
        public ActionResult Index(string userName = "", string dateFilter = "", string sortBy = "")
        {
            string userId = User.Identity.GetUserId();
            if (!RepositoryQueries.isUserManager(userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            Synagogue currSynagogue = RepositoryQueries.GetManagerSynagogue(userId);
            ViewBag.allChairs = RepositoryQueries.GetAllChairsInSynagogue(currSynagogue.Id);

            IQueryable<Absence> absences = RepositoryQueries.GetAbsencesBySynagogue(currSynagogue.Id);

            List<AbsenceViewModel> absencesViewModel = absences.Select(delegate (Absence absence) { return AbsenceViewModel.FromAbsence(absence); }).ToList();

            if (userName != String.Empty) {
                absencesViewModel = absencesViewModel.Where(absence => absence.User.UserName.Contains(userName)).ToList();
            }

            if (dateFilter != String.Empty)
            {
                dateFilter = DateTime.Parse(dateFilter).ToString("MM/dd/yyyy");
                absencesViewModel = absencesViewModel.Where(absence => absence.Date == dateFilter).ToList();
            }

            if (sortBy == "date")
            {
                absencesViewModel = absencesViewModel.OrderBy(a => a.Date).ToList();
            }
            else if (sortBy == "user")
            {
                absencesViewModel = absencesViewModel.OrderBy(a => a.User.UserName).ToList();
            }

            ViewBag.userName = userName;
            ViewBag.dateFilter = dateFilter;

            return View(absencesViewModel);
        }

        // GET: Absences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Absence absence = RepositoryQueries.getAbsenceIncludeUserAndSynagogue(id.Value);
            if (absence == null)
            {
                return HttpNotFound();
            }
            string userId = User.Identity.GetUserId();
            if (!RepositoryQueries.isUserPermittedToReportAbsenceForChairs(userId, absence.Chairs))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            ViewBag.isManager = RepositoryQueries.isUserManager(userId);

            AbsenceViewModel absenceViewModel = AbsenceViewModel.FromAbsence(absence);

            ViewBag.allChairs = RepositoryQueries.GetAllChairsInSynagogue(absenceViewModel.Synagogue.Id);
            // without synagogue to void circular
            ViewBag.selectedChairs = absence.Chairs.Select(chair =>  new Chair()
            {
                Id = chair.Id,
                I = chair.I,
                J = chair.J,
                SerialNumber = chair.SerialNumber,
                User = chair.User
            });

            return View(absenceViewModel);
        }

        // GET: Absences/Create
        public ActionResult Create()
        {
            string userId = User.Identity.GetUserId();
            prepareBeforeCreateView(userId);
            return View();
        }

        // POST: Absences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Date,Chairs")] Absence absence)
        {
            string userId = User.Identity.GetUserId();
            string errorMessage = String.Empty;

            if (absence.Date == null || absence.Date == DateTime.MinValue)
            {
                errorMessage = "no shabat had been selected";
            }
            else if (absence.Chairs == null || absence.Chairs.Count() == 0)
            {
                errorMessage = "no chair had been selected";
            }
            else if (absence.Date < DateTime.Now)
            {
                errorMessage = "date of report had passed";
            }
            else {
                IQueryable<Chair> chairs = RepositoryQueries.getDbChairsIncludeUserAndSynagogue(absence.Chairs);
                if (!RepositoryQueries.isUserPermittedToReportAbsenceForChairs(userId, chairs))
                {
                    errorMessage = "you are not permitted to report about the selected chairs";
                }
                else if (RepositoryQueries.isAbsenceExistForChairs(chairs, absence.Date))
                {
                    errorMessage = "Duplicate report - one or more chairs had been reported before";
                }
                else
                {
                    var groupedChairs = chairs.GroupBy(chair => chair.User).ToList();

                    List<Absence> absencesPerUser = new List<Absence>() { };
                    groupedChairs.ForEach(userChairs => absencesPerUser.Add(new Absence()
                    {
                        Date = absence.Date,
                        Chairs = userChairs.ToList()
                    }));

                    IEnumerable<Absence> absences = RepositoryQueries.db.Absences.AddRange(absencesPerUser);

                    RepositoryQueries.db.SaveChanges();

                    string urlToReturn;
                    if (absences.Count() > 1)
                    {
                        urlToReturn = "/Absences/index";
                    }
                    else
                    {
                        urlToReturn = "/Absences/Details/" + absences.First().Id;
                    }
                    ContentResult result = new ContentResult();
                    result.Content = urlToReturn;
                    return result;
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, errorMessage);
        }

        private void prepareBeforeCreateView(string userId) {
            
            Synagogue currSynagogue;
            IEnumerable<Chair> chairsOptions = null;
            IEnumerable<Chair> allChairs = null;

            bool isManager = RepositoryQueries.isUserManager(userId);
            if (isManager)
            {
                currSynagogue = RepositoryQueries.GetManagerSynagogue(userId);
                allChairs = RepositoryQueries.GetAllChairsInSynagogue(currSynagogue.Id);
                chairsOptions = allChairs.Where(c => c.User != null);
            }
            else
            {
                currSynagogue = RepositoryQueries.GetUserSynagogue(userId);
                if (currSynagogue != null)
                {
                    chairsOptions = RepositoryQueries.GetUserChairsInSynagogue(userId, currSynagogue.Id);
                    allChairs = RepositoryQueries.GetAllChairsInSynagogue(currSynagogue.Id);
                }
            }

            ViewBag.allChairs = allChairs;
            ViewBag.isManager = isManager;
            ViewBag.currSynagogue = currSynagogue;
            ViewBag.chairsNumbersOptions = chairsOptions.Select(chair => chair.SerialNumber);
        }

        // GET: Absences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Absence absence = RepositoryQueries.getAbsenceIncludeUserAndSynagogue(id.Value);
            //Absence absence = db.Absences.Include(a=>a.Chairs).FirstOrDefault(a => a.Id == id.Value);
            if (absence == null)
            {
                return HttpNotFound();
            }
            AbsenceViewModel absenceViewModel = AbsenceViewModel.FromAbsence(absence);
            string userId = User.Identity.GetUserId();
            bool isManager = RepositoryQueries.isUserManager(userId);
            if (absenceViewModel.User == null || (!isManager && absenceViewModel.User.Id != userId)) {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            IEnumerable<Chair> allChairs = RepositoryQueries.GetAllChairsInSynagogue(absenceViewModel.Synagogue.Id);
            IEnumerable<Chair> chairsOptions = RepositoryQueries.GetUserChairsInSynagogue(absenceViewModel.User.Id, absenceViewModel.Synagogue.Id);

            ViewBag.allChairs = allChairs;
            ViewBag.isManager = isManager;
            ViewBag.chairsNumbersOptions = chairsOptions.Select(chair => chair.SerialNumber);

            return View(absenceViewModel);
        }

        // POST: Absences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,Chairs")] Absence absence)
        {
            string userId = User.Identity.GetUserId();
            string errorMessage = String.Empty;

            if (absence.Date == null || absence.Date == DateTime.MinValue)
            {
                errorMessage = "no shabat had been selected";
            }
            else if (absence.Chairs == null || absence.Chairs.Count() == 0)
            {
                errorMessage = "no chair had been selected";
            }
            else if (absence.Date < DateTime.Now)
            {

resitproject_new/resitproject_new/Controllers/SynagogueManagerController.cs
using Microsoft.AspNet.Identity;
using resitproject_new.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using resitproject_new.DAL;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using System.Data.Entity;
using resitproject_new.BL;

namespace resitproject_new.Controllers
{
    public class SynagogueManagerController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        private static ApplicationUserManager _userManager;
        

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: SynagogueManager
        public ActionResult Index()
        {
           
            if (User.Identity.GetUserId() != null)
            {
                Synagogue synagogue = RepositoryQueries.GetManagerSynagogue(User.Identity.GetUserId());
                if (synagogue != null)
                {
                    return View(synagogue);
                }

                
            }
            return HttpNotFound();
        }

        private void prepareBeforeCreateView(string userId)
        {

            Synagogue currSynagogue;
            IEnumerable<Chair> chairsOptions = null;
            IEnumerable<Chair> allChairs = null;

            bool isManager = RepositoryQueries.isUserManager(userId);
            if (isManager)
            {
                currSynagogue = RepositoryQueries.GetManagerSynagogue(userId);
                chairsOptions = RepositoryQueries.GetAllChairsInSynagogue(currSynagogue.Id);
                allChairs = chairsOptions;
            }
            else
            {
                currSynagogue = RepositoryQueries.GetUserSynagogue(userId);
                if (currSynagogue != null)
                {
                    chairsOptions = RepositoryQueries.GetUserChairsInSynagogue(userId, currSynagogue.Id);
                    allChairs = RepositoryQueries.GetAllChairsInSynagogue(currSynagogue.Id);
                }
            }

            ViewBag.allChairs = allChairs;
            ViewBag.isManager = isManager;
            ViewBag.currSynagogue = currSynagogue;
            ViewBag.chairsNumbersOptions = chairsOptions.Select(chair => chair.SerialNumber);
        }

        public ActionResult GetAllUsers(int synagogueId)
        {
            if (User.Identity == null ||  !RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId)) 
            {
                return HttpNotFound();
            }

            var chairs = RepositoryQueries.GetAllChairsInSynagogue(synagogueId).Where(c => c.User != null);
            var charisByUsers = chairs.GroupBy(c => c.User).Select(u => new ChairsUserViewModel {User = u.Key, Chairs = u.Select(p => p.SerialNumber).ToList() }).ToList();
          
            ViewBag.synagogueId = synagogueId;
            return View(charisByUsers);
        }


        public ActionResult CreateUser(int synagogueId)
        {
            if (User.Identity == null || !RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId))
            {
                return HttpNotFound();
            }
            ViewBag.chairsList =  db.Chairs.Where(c => c.Synagogue.Id == synagogueId).Select(c => c.SerialNumber);
            ViewBag.synagogueId = synagogueId;
            prepareBeforeCreateView(User.Identity.GetUserId());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateUser(int synagogueId,[Bind(Include = "User, Chairs")] ChairsUserViewModel model)
        {
            ApplicationUser user = UserManager.FindByEmailAsync(model.User.Email).Result;

            if (user == null)
            {
                user = new ApplicationUser { UserName = model.User.Email, Email = model.User.Email, PhoneNumber = model.User.PhoneNumber };
                await UserManager.CreateAsync(user, "Aa123456!");

            }
            foreach (var item in model.Chairs)
            {
                var chair = RepositoryQueries.GetChairBySerialNumberOfSynagogueId(item, synagogueId);
                RepositoryQueries.UpdateUserChair(chair, user.Id);
            }
           
            return RedirectToAction("GetAllUsers", new { synagogueId = synagogueId });
            
        }


        public ActionResult EditUser(string userId, int synagogueId)
        {
            if (User.Identity == null || !RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId))
            {
                return HttpNotFound();
            }
            var user = _userManager.FindById(userId);
            return View();
        }

        public ActionResult DeleteUser(string userId, int synagogueId)
        {
            if (User.Identity == null || !RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId))
            {
                return HttpNotFound();
            }
            var user = UserManager.FindById(userId);
            var chairs = RepositoryQueries.GetUserChairsInSynagogue(userId, synagogueId);
            ViewBag.synagogueId = synagogueId;
            return View(new ChairsUserViewModel() { User = user, Chairs = chairs.Select(c => c.SerialNumber).ToList() });
        }

        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUserConfirmed(string userId, int synagogueId)
        {
            var chiars =  RepositoryQueries.GetUserChairsInSynagogue(userId, synagogueId);
            var Synagogue = RepositoryQueries.GetManagerSynagogue(User.Identity.GetUserId());
            foreach (var chiar in chiars)
            {
                chiar.Synagogue = Synagogue;
                RepositoryQueries.UpdateUserChair(chiar, null);
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult Statistics(int synagogueId)
        {
            if (User.Identity == null || !RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId))
            {
                return HttpNotFound();
            }
            var statisticsSynagogue = new StatisticsSynagogue(synagogueId);
            return View(new List<StatisticsViewModel>() { statisticsSynagogue.GetStatisticsByUsers(), statisticsSynagogue.GetStatisticsByDates() });
        }
        
    }

}

resitproject_new/resitproject_new/Views/SynagogueManager/CreateUser.cshtml
@model resitproject_new.Models.ChairsUserViewModel

@{
    ViewBag.Title = "CreateUser";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.User.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chairs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Chairs, new SelectList(ViewBag.chairsList), new { multiple = "multiple" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateUser" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div id="mapContainer"></div>
<div>
    @Html.ActionLink("Back to List", "GetAllUsers")
</div>

@section Scripts {
    @Styles.Render("~/Content/ShabatPickerComponent.css")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/lib/ChairsMapHandler.js")
    @Scripts.Render("~/Scripts/lib/ShabatsProvider.js")
    @Scripts.Render("~/Scripts/lib/ShabatPickerComponent.js")
    @Scripts.Render("~/Scripts/lib/AbsenceFormHandler.js")

    <script>
        $(document).ready(() => {
            //const allChairs = JSON.parse('@Html.Raw(Json.Encode(ViewBag.allChairs))');
            //const selectableChairsSerialNumbers = JSON.parse('@Html.Raw(Json.Encode(ViewBag.chairsNumbersOptions))');

            //const absenceFormHandler = new AbsenceFormHandler(allChairs, selectableChairsSerialNumbers);
            //absenceFormHandler.handleForm();


            const allChairs = JSON.parse('@Html.Raw(Json.Encode(ViewBag.allChairs))');
            const selectableChairsSerialNumbers = JSON.parse('@Html.Raw(Json.Encode(ViewBag.chairsNumbersOptions))');

            const absenceFormHandler = new AbsenceFormHandler(allChairs, selectableChairsSerialNumbers);
            absenceFormHandler.handleForm();


        });

    </script>
}

resitproject_new/resitproject_new/Views/SynagogueManager/DeleteUser.cshtml
@model resitproject_new.Models.ChairsUserViewModel

@{
    ViewBag.Title = "הסר מתפלל";
}


<h3>?האם אתה בטוח שברצונך להסיר מתפלל</h3>
<div>
    <h4>Synagogue</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Chairs)
        </dt>

        <dd>
            @{
                var chairs = "";
                foreach (var chair in Model.Chairs)
                {
                    chairs += chair + ",";
                }
                chairs = chairs.Substring(0, chairs.Length - 1);

            }
        </dd>

    </dl>
    
    @using (Html.BeginForm( "DeleteUser", "SynagogueManager", routeValues: new { userId = Model.User.Id,  synagogueId = ViewBag.synagogueId },method: FormMethod.Post ))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("חזור לרשימת מתפללים", "GetAllUser", new { synagogueId = ViewBag.synagogueId })
        </div>
    }
</div>

resitproject_new/resitproject_new/Views/SynagogueManager/EditUser.cshtml
@{
    ViewBag.Title = "EditUser";
}

<h2>EditUser</h2>

resitproject_new/resitproject_new/Views/SynagogueManager/GetAllUsers.cshtml
<head>
    <link rel='stylesheet' type='text/css' href='~/Content/GetallUsers.css'>
</head>
@model IEnumerable<resitproject_new.Models.ChairsUserViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>מתפללים קבועים</h2>

<p>
    @Html.ActionLink("Create New", "CreateUser", new { synagogueId = ViewBag.synagogueId }, new { synagogueId = ViewBag.synagogueId })
</p>
<div class="form-group">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
        <input type="text" id="search1" placeholder="Search">
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
                @Html.DisplayNameFor(model => model.Chairs)
            </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr class="stl">
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td> 
        <td>
            @{
                var chairs = "";
                foreach (var chair in item.Chairs)
                {
                    chairs += chair + ",";
                }
                chairs = chairs.Substring(0, chairs.Length - 1);
                <p>@chairs</p>
            }
            
        </td>
        <td>
            @*@Html.ActionLink("EditUser", "Edit", new { userId = item.User.Id }) |*@
            
            @Html.ActionLink("Delete", "DeleteUser", new { userId = item.User.Id, synagogueId = ViewBag.synagogueId})
        </td>
    </tr>
    }

</table>
<div class="UploadUsers">
    @using (Html.BeginForm("UploadUsers", "Synagogues", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <h6>טען מתפלללים מקובץ</h6>
        <div class="uploadusers">

            @{
                if (Model != null)
                {
                    @Html.TextBox("file", "", new { type = "file" }) <br />

                    <input type="hidden"
                           name="synagogueId"
                           value="@ViewBag.synagogueId">
                    <input class="inputfile" type="submit" value="UploadUsers" />
                }
            }


            @ViewBag.Message

        </div>


                }
</div>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    $(document).ready(function () {
        function ts(t1, t2) {
            if (t1.indexOf(t2) != -1)
                return true;
            else
                return false;
        }
        $("#search1").keyup(function () {
            var st = $("#search1 ").val().toLowerCase();
            $(".stl").each(function () {
                if (!ts($(this).text().toLowerCase(), st)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            });

        });
    });
</script>
<script>
    $(document).ready(function () {
        $("table").css({ "background-color": "burlywood" });
    });
</script>

resitproject_new/resitproject_new/Views/SynagogueManager/Index.cshtml
﻿<link rel='stylesheet' type='text/css' href='~/Content/ManagerHomePage.css'>
@model resitproject_new.Models.Synagogue
@{
    ViewBag.Title = Model.Name;
}


<h3>
    @Html.DisplayFor(model => model.Name)
</h3>
<div class="multycolman">
    
    <div class="divlist1">
        <ul class="list1" style="list-style-type:none;border:1px #000000;width:100px; margin-left:475px;
border-color:antiquewhite !important;background-color:lightgray;border-top-left-radius:22px;border-top-right-radius:18px;
color:darkslategray;font-family:Arial;font-weight: bold;font-size:15px">
         
            <li>לא תרצח </li>
            <li>לא תנאף</li>
            <li>לא תגנב</li>
            <li>לא תענה </li>
            <li>לא תחמד</li>
        </ul>
    </div>
    <div class="divlist2">
        <ul class="list2" style="list-style-type:none;border:1px #000000;width:100px;margin-right:475px;border-color:antiquewhite !important
    ;background-color:lightgray;border-top-left-radius:22px;border-top-right-radius:22px;color:darkslategray;
     font-family:Arial;font-weight: bold;font-size:15px;text-align:center;">
            <li>אנכי ה</li>
            <li>לא יהיה</li>
            <li>לא תשא </li>
            <li>זכור את</li>
            <li>כבד את</li>
        </ul>
    </div>
    </div>
<div class="table">
    <table class="tablemenue">
        <tr>
            <th>
                <div>
                    @Html.ActionLink("פרטי בית הכנסת ", "Details", "Synagogues", new { id = Model.Id }, new { id = Model.Id })
                </div>
            </th>
            <th>
                <div>
                    @Html.ActionLink("הצג מפה", "GetChairs", "Synagogues", new { SynagogueId = Model.Id }, new { SynagogueId = Model.Id })
                </div>
            </th>
            <th>
                <div>
                    @Html.ActionLink("הצג מתפללים", "GetAllUsers", new { SynagogueId = Model.Id }, new { SynagogueId = Model.Id })
                </div>
            </th>

            <th>
                <div>
                    @Html.ActionLink("חיסורים", "Index", "Absences", new { SynagogueId = Model.Id }, new { SynagogueId = Model.Id })
                </div>
            </th>
            <th>
                <div>
                    @Html.ActionLink("סטיסטיקה", "Statistics", "SynagogueManager", new { SynagogueId = Model.Id }, new { SynagogueId = Model.Id })
                </div>
            </th>

        </tr>

    </table>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/lib/ShabatsProvider.js"></script>
<script>
   
</script>
 

resitproject_new/resitproject_new/Views/SynagogueManager/Statistics.cshtml
@model IEnumerable<resitproject_new.Models.StatisticsViewModel>

<div id="statistics-main">

    @foreach (var item in Model)
    {
        <div class="statistics-header">
            @Html.DisplayFor(modelItem => item.HebrewTitle)
        </div>
        <svg class="statistics-graph" id="@item.Title"></svg>

    }
</div>

@section Scripts {
    @Styles.Render("~/Scripts/d3/d3.css")
    @Scripts.Render("~/Scripts/d3/d3.v3.min.js")
    @Scripts.Render("~/Scripts/d3/d3-resit.js")
    <script>
            var data = JSON.parse('@Html.Raw(Json.Encode(Model))')
            for (var i = 0; i < data.length; i++) {
                createHisogram(data[i].Title, data[i]);
            }
    </script>


}