resitproject_new/resitproject_new/Models/Chair.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace resitproject_new.Models
{
    public class Chair
    {
        public int Id { get; set; }
        public int I { get; set; }
        public int J { get; set; }
        [Display(Name = "מספר כסא")]
        public int SerialNumber { get; set; }
        public Synagogue Synagogue { get; set; }
        public ApplicationUser User { get; set; }
        public ICollection<Absence> Absences { get; set; }

    }
}

resitproject_new/resitproject_new/Controllers/ChairsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using resitproject_new.BL;
using resitproject_new.DAL;
using resitproject_new.Models;

namespace resitproject_new.Controllers
{
    public class ChairsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private static ApplicationUserManager _userManager;
        private CSVReader _CSVReader;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public CSVReader cSVReader
        {
            get
            {
                return _CSVReader ?? CSVReader.Create(UserManager);
            }
            private set
            {
                _CSVReader = value;
            }
        }

        // GET: Chairs
        public ActionResult Index()
        {
            return View(db.Chairs.ToList());
        }

        [HttpGet]
        public ActionResult UploadChairs(int synagogueId)
        {

            Synagogue synagogue = db.Synagogues.Include(s => s.Manager).FirstOrDefault(s => s.Id == synagogueId);
            if (User.Identity.GetUserId() == synagogue.Manager.Id)
            {
                return View(synagogue);
            }
            else
            {
                ViewBag.Message = "אינך רשאי לבצע פעולה זו!";
                return View();
            }

        }

        [HttpPost]
        public ActionResult UploadChairs(HttpPostedFileBase file, int synagogueId)
        {

            try
            {
                Synagogue synagogue = db.Synagogues.Find(synagogueId);
                if (RepositoryQueries.isUserManagerOfSynagogue(User.Identity.GetUserId(), synagogueId) && file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    file.SaveAs(_path);

                    try
                    {

                        cSVReader.ReadChairCsv(_path, synagogue);
                        ViewBag.Message = "File Uploaded Successfully!!";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "Chairs not saved";
                        Console.WriteLine(ex.Message);
                    }

                }

                return RedirectToAction("GetChairs", "Synagogues", new { synagogueId = synagogueId });
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }

        // GET: Chairs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = db.Chairs.Find(id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            return View(chair);
        }

        // GET: Chairs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chairs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,I,J")] Chair chair)
        {
            if (ModelState.IsValid)
            {
                db.Chairs.Add(chair);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chair);
        }

        // GET: Chairs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = db.Chairs.Find(id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            return View(chair);
        }

        // POST: Chairs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,I,J")] Chair chair)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chair).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chair);
        }

        // GET: Chairs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chair chair = db.Chairs.Find(id);
            if (chair == null)
            {
                return HttpNotFound();
            }
            return View(chair);
        }

        // POST: Chairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chair chair = db.Chairs.Find(id);
            db.Chairs.Remove(chair);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

resitproject_new/resitproject_new/Views/Chairs/Create.cshtml
@model resitproject_new.Models.Chair

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chair</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.I, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.I, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.I, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.J, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.J, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.J, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

resitproject_new/resitproject_new/Views/Chairs/Delete.cshtml
@model resitproject_new.Models.Chair

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chair</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.I)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.I)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.J)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.J)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

resitproject_new/resitproject_new/Views/Chairs/Details.cshtml
@model resitproject_new.Models.Chair

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Chair</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.I)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.I)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.J)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.J)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

resitproject_new/resitproject_new/Views/Chairs/Edit.cshtml
@model resitproject_new.Models.Chair

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chair</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.I, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.I, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.I, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.J, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.J, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.J, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

resitproject_new/resitproject_new/Views/Chairs/Index.cshtml
@model IEnumerable<resitproject_new.Models.Chair>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.I)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.J)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.I)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.J)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SerialNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

resitproject_new/resitproject_new/Views/Chairs/UploadChairs.cshtml
@model resitproject_new.Models.Synagogue

@{
    ViewBag.Title = " העלה קובץ";
}

<h2>UploadFile</h2>
<h3>
    @Html.DisplayFor(model => model.Name)
</h3>

@using (Html.BeginForm("UploadChairs", "Chairs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h1></h1>
    <div>
        @{
            if (Model != null)
            {
                @Html.TextBox("file", "", new { type = "file" }) <br />
                <input type="hidden"
                       name="synagogueId"
                       value="@Html.Raw(Model.Id)">
                <input type="submit" value="UploadChairs" />
                }
            }
                @ViewBag.Message

            </div>


}  